export const levels = [
  { id: 'preschool', short: 'Pre-K', label: 'First sounds', shelf: 'Tiny sound stories' },
  { id: 'kindy', short: 'Kindy', label: 'Short words', shelf: 'Kindy favourites' },
  { id: 'year1', short: 'Year 1', label: 'New readers', shelf: 'Stories to grow with' },
  { id: 'year2', short: 'Year 2', label: 'Growing strong', shelf: 'Bigger adventures' },
  { id: 'year3', short: 'Year 3', label: 'Confident', shelf: 'Curious chapter starts' },
]

// Sound groups for the scaffolded Pre-K and Kindy reader. These are authored
// explicitly because English spelling cannot be segmented reliably by a simple
// letter-pair rule. Add and review entries when adding early-reader stories.
export const earlyReaderCueGroups = {
  a: ['a'],
  at: ['a', 't'],
  bath: ['b', 'a', 'th'],
  bee: ['b', 'ee'],
  big: ['b', 'i', 'g'],
  bag: ['b', 'a', 'g'],
  by: ['b', 'y'],
  can: ['c', 'a', 'n'],
  c: ['c'],
  cat: ['c', 'a', 't'],
  dad: ['d', 'a', 'd'],
  frog: ['f', 'r', 'o', 'g'],
  goes: ['g', 'oe', 's'],
  got: ['g', 'o', 't'],
  green: ['g', 'r', 'ee', 'n'],
  goose: ['g', 'oo', 's', 'e'],
  had: ['h', 'a', 'd'],
  h: ['h'],
  hat: ['h', 'a', 't'],
  he: ['h', 'e'],
  her: ['h', 'er'],
  his: ['h', 'i', 's'],
  hop: ['h', 'o', 'p'],
  hops: ['h', 'o', 'p', 's'],
  i: ['i'],
  in: ['i', 'n'],
  is: ['i', 's'],
  it: ['i', 't'],
  log: ['l', 'o', 'g'],
  loose: ['l', 'oo', 's', 'e'],
  m: ['m'],
  map: ['m', 'a', 'p'],
  mat: ['m', 'a', 't'],
  moon: ['m', 'oo', 'n'],
  mud: ['m', 'u', 'd'],
  my: ['m', 'y'],
  n: ['n'],
  nap: ['n', 'a', 'p'],
  on: ['o', 'n'],
  need: ['n', 'ee', 'd'],
  past: ['p', 'a', 's', 't'],
  paws: ['p', 'aw', 's'],
  p: ['p'],
  pip: ['p', 'i', 'p'],
  pat: ['p', 'a', 't'],
  pop: ['p', 'o', 'p'],
  pup: ['p', 'u', 'p'],
  quick: ['qu', 'i', 'ck'],
  rat: ['r', 'a', 't'],
  r: ['r'],
  red: ['r', 'e', 'd'],
  run: ['r', 'u', 'n'],
  s: ['s'],
  sat: ['s', 'a', 't'],
  saw: ['s', 'aw'],
  see: ['s', 'ee'],
  she: ['sh', 'e'],
  small: ['s', 'm', 'a', 'll'],
  splash: ['s', 'p', 'l', 'a', 'sh'],
  star: ['s', 't', 'ar'],
  sun: ['s', 'u', 'n'],
  t: ['t'],
  to: ['t', 'o'],
  f: ['f'],
  the: ['th', 'e'],
  up: ['u', 'p'],
  we: ['w', 'e'],
  wet: ['w', 'e', 't'],
  winked: ['w', 'i', 'n', 'k', 'ed'],
}

// Word-specific exceptions that affect how cues are presented. Indexes refer
// to the authored groups above. Silent groups remain visible in the word, but
// receive no rail segment and cannot become the active sound.
export const earlyReaderWordFeatures = {
  goose: { silentGroups: [3] },
  loose: { silentGroups: [3] },
}

// How each sound should be travelled during continuous blending. A `hold`
// sound can be sustained cleanly; a `quick` sound is shown briefly so children
// are not encouraged to add an "uh" after a stop consonant.
export const earlyReaderSoundTiming = {
  a: 'hold',
  ar: 'hold',
  aw: 'hold',
  b: 'quick',
  c: 'quick',
  ch: 'quick',
  ck: 'quick',
  d: 'quick',
  e: 'hold',
  ed: 'quick',
  ee: 'hold',
  er: 'hold',
  f: 'hold',
  g: 'quick',
  h: 'hold',
  i: 'hold',
  j: 'quick',
  k: 'quick',
  l: 'hold',
  ll: 'hold',
  m: 'hold',
  n: 'hold',
  o: 'hold',
  oe: 'hold',
  oo: 'hold',
  p: 'quick',
  qu: 'quick',
  r: 'hold',
  s: 'hold',
  sh: 'hold',
  t: 'quick',
  th: 'hold',
  u: 'hold',
  v: 'hold',
  w: 'hold',
  x: 'quick',
  y: 'hold',
  z: 'hold',
}

export const stories = [
  {
    id: 'first-sounds', level: 'preschool', mode: 'sound', title: 'First Sounds', art: '🍎',
    sentences: ['m', 's', 'a', 't'],
    pictures: [
      { symbol: '🌙', label: 'moon' },
      { symbol: '🐍', label: 'snake' },
      { symbol: '🍎', label: 'apple' },
      { symbol: '🐢', label: 'turtle' },
    ],
  },
  {
    id: 'more-sounds', level: 'preschool', mode: 'sound', title: 'More Sounds', art: '🐟',
    sentences: ['n', 'p', 'i', 'f'],
    pictures: [
      { symbol: '🪺', label: 'nest' },
      { symbol: '🐷', label: 'pig' },
      { symbol: '🐜', label: 'insect' },
      { symbol: '🐟', label: 'fish' },
    ],
  },
  {
    id: 'ready-for-words', level: 'preschool', mode: 'sound', title: 'Ready for Words', art: '🐈',
    sentences: ['c', 'h', 'r'],
    pictures: [
      { symbol: '🐈', label: 'cat' },
      { symbol: '🎩', label: 'hat' },
      { symbol: '🐀', label: 'rat' },
    ],
  },
  {
    id: 'tiny-words', level: 'preschool', mode: 'word', title: 'Tiny Words', art: '🗺️',
    sentences: ['cat', 'hat', 'map', 'rat'],
    pictures: [
      { symbol: '🐈', label: 'cat' },
      { symbol: '🎩', label: 'hat' },
      { symbol: '🗺️', label: 'map' },
      { symbol: '🐀', label: 'rat' },
    ],
  },
  { id: 'mud-pup', level: 'kindy', title: 'Pip the Pup', art: '🐶', sentences: ['Pip sat.', 'Pip got wet.', 'Pat, pat, Pip.'] },
  { id: 'cat-mat', level: 'kindy', title: 'Cat on a Mat', art: '🐈', sentences: ['Cat sat.', 'Cat sat on a mat.', 'Cat had a nap.'] },
  { id: 'red-hat', level: 'kindy', title: 'A Red Hat', art: '🎩', sentences: ['A red hat.', 'A big bag.', 'Pop it in!'] },
  { id: 'run-pup', level: 'kindy', title: 'Run, Pup!', art: '🐕', sentences: ['Run, pup!', 'Run to Dad.', 'Pat, pat, pup.'] },
  { id: 'moon-cat', level: 'year1', title: 'The Moon Cat', art: '🌙', sentences: ['A cat sat by the moon.', 'She saw a small star.', 'The star winked at her.'] },
  { id: 'frog-hop', level: 'year1', title: 'Hop, Frog!', art: '🐸', sentences: ['A green frog can hop.', 'He hops past a log.', 'Splash goes the frog!'] },
  { id: 'loose-goose', level: 'year1', title: 'Loose Goose', art: '🪿', sentences: ['A goose got loose.', 'The goose is in mud.', 'The goose had a bath.'] },
  { id: 'seed', level: 'year1', title: 'The Brave Seed', art: '🌱', sentences: ['A little seed slept underground.', 'Warm rain tapped the soil.', 'At last, a green shoot appeared.'] },
  { id: 'kite', level: 'year1', title: 'Kite Day', art: '🪁', sentences: ['Mina made a bright orange kite.', 'The wind lifted it over the trees.', 'She held the string tight.', 'Then the wind dropped, and the kite landed in Dad’s hat.', 'Mina laughed as they untangled the string.'] },
  { id: 'night-bus', level: 'year1', title: 'The Night Bus', art: '🚌', sentences: ['The last bus rolled down our street.', 'Its windows glowed like tiny moons.', 'Dad and I waved goodnight.'] },
  { id: 'crab', level: 'year2', title: 'Crab’s New Home', art: '🦀', sentences: ['Cora the crab needed a larger shell.', 'She searched beneath the quiet rocks.', 'A smooth striped shell fit perfectly.'] },
  { id: 'cloud', level: 'year2', title: 'Cloud Collector', art: '☁️', sentences: ['Noah liked to name the passing clouds.', 'One looked exactly like a dancing bear.', 'Another became a ship with silver sails.'] },
  { id: 'garden', level: 'year3', title: 'The Secret Garden Gate', art: '🌳', sentences: ['Behind the old shed, Amari discovered a tiny blue gate.', 'It opened into a garden filled with humming flowers.', 'At the centre stood a tree with golden leaves.', 'Under its branches, a wooden sign read: Please help us grow.', 'Amari fetched a watering can and gave every flower a drink.', 'The next morning, one tiny golden leaf waited by the gate.'] },
  { id: 'lighthouse', level: 'year3', title: 'Lighthouse Mystery', art: '🔦', sentences: ['Each evening, the lighthouse flashed across the restless sea.', 'One stormy night, the bright beam suddenly disappeared.', 'Zoe pulled on her boots and hurried up the hill with Dad.', 'Inside, the keeper was searching for his spare lamp in the dark.', 'Zoe shone her torch while Dad helped him fit it into place.', 'The beam swept across the waves again, guiding a fishing boat home.'] },
]
